FROM alpine:latest
LABEL maintainer="d7xdev"

RUN apk add --no-cache --update \
        xeyes \
    && rm -rf ~/.cache/* /usr/local/share/man /tmp/*                                               

CMD ["/usr/bin/xeyes", "-outline", "black", "-center", "white", "-fg", "black"]
